version: '3.8'

services:
  backend:
    build:
      context: ./Techdome-backend
    container_name: backend_image
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_NAME=techdome_db
      - CLOUD_NAME=your_cloud_name
      - API_KEY=your_api_key
      - API_SECRET=your_api_secret
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: techdome_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  frontend:
    build:
      context: ./Techdome-frontend
    container_name: frontend_image
    ports:
      - "3001:80"  # Expose port 80 of the Nginx container
    depends_on:
      - backend

volumes:
  mysql-data:
